WIP:added more test
pusewicz/refile-cloudinary pull request #5
Opened 2018-02-23 01:54 UTC by BCecatto

###Why this PR?
Increase number of test

2018-02-23 05:58 UTC, pusewicz commented on spec/refile/cloudinary_spec.rb
> +RSpec.describe Refile::Cloudinary do
@BCecatto 👋 and thanks for the PR! Please move the `config` variable here as:

```ruby
let(:config) {{
  cloud_name: "hfkkd49r3",
  api_key: "some-key",
  api_secret: "some-secret"
}}
```

2018-02-23 05:58 UTC, pusewicz commented on spec/refile/cloudinary_spec.rb
> +
✂️ the empty line 😄

2018-02-23 05:58 UTC, pusewicz commented on spec/refile/cloudinary_spec.rb
> +
✂️ the empty line here too! 😄

2018-02-23 05:59 UTC, pusewicz requested changes
Thanks a lot for the PR! Please make these changes and I'll merge this 😸

2018-02-23 05:59 UTC, pusewicz commented on spec/refile/cloudinary_spec.rb
> +      expect(backend).to be_truthy
I'd probably change this to `.not_to be_nil` to match the test description.

2018-02-26 08:31 UTC, pusewicz commented on spec/refile/cloudinary_spec.rb
> +      expect(backend.max_size).to be <= 10_485_760
This test does not make much sense. I'd drop this one.

2018-02-26 08:31 UTC, pusewicz commented on spec/refile/cloudinary_spec.rb
> +      expect(backend.max_size).to_not be > 10_485_760
I'd drop this one too.

2018-02-26 08:32 UTC, pusewicz commented on spec/refile/cloudinary_spec.rb
> +    end
This test is fine. I'd write another test where you initialise the backend with a different value for `max_size` and test that the accessor correctly returns it.

2018-02-26 08:32 UTC, pusewicz commented on spec/refile/cloudinary_spec.rb
> +    let(:backend) { Refile::Cloudinary.new( {**config} ) }
Why `{**config}`? I'd simply pass `config` instead.

2018-02-26 08:33 UTC, pusewicz commented on spec/refile/cloudinary_spec.rb
> +      expect(backend).not_to be_nil
Please fix these automated messages.

2018-02-26 08:33 UTC, pusewicz commented on refile-cloudinary.gemspec
> +  spec.add_dependency             "cloudinary", "~> 1.1.7"
Why did you change the order? It was sorted alphabetically before.

2018-02-26 08:34 UTC, pusewicz requested changes
Thanks! I left some comments and I'd like those changes to be made before merging.

2018-02-27 22:30 UTC, BCecatto commented
What need more?

2018-02-28 07:03 UTC, pusewicz commented on spec/refile/cloudinary_spec.rb
> +    let(:backend_default) { Refile::Cloudinary.new(**config) }
Please remove the `**`, they are not necessary and might be confusing to people looking at those.

2018-02-28 07:04 UTC, pusewicz commented on spec/refile/cloudinary_spec.rb
> +    it "change to 100 max_size" do
Please add new lines between the blocks.

2018-02-28 07:04 UTC, pusewicz commented on spec/refile/cloudinary_spec.rb
> +      expect(backend_default).not_to be_nil
There's still some trailing space as you can see in the comment above.

2018-02-28 07:05 UTC, pusewicz commented
Hey @BCecatto, thanks for the updates! I've added few new comments, we are really close to getting this merged!

2018-02-28 15:08 UTC, pusewicz commented on spec/refile/cloudinary_spec.rb
> +    let(:backend_max_size_100) { Refile::Cloudinary.new({ **config }, max_size: 100) }
This like too, please :), no need for the `**`.

2019-03-18 13:05 UTC, sobrinho commented
Can be closed in favor of #9.

2019-03-18 14:30 UTC, pusewicz commented
Closing due to inactivity.

2019-03-18 14:30 UTC, closed without merging